export const pages = [
  {
    id: 0,
    title: "",
    content:
      '<section class="list-result"><h1>Consult Best Wills / Trusts Lawyers / Advocates in India</h1><br /><p> A seasoned lawyer will be able to help you legally determine how your assets will be managed during your lifetime and how to distribute them after your death. Because it\'s impossible for anyone to explain a will after his or her death, it is very important that the will meets all legal requirements. Use LawRato to hire a top rated lawyer in India to draft and register your Will, form a trust and drafting a trust deed.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are will and trusts?</h2>Trusts and Wills allow you to dictate how your property will be disposed in your absence due to your death. <br>A Will is document that sets out how your estate should be divided among your legal heirs after your demise.<br>A Trust allows you to transfer property to a third person who will hold and use the property for a beneficiary of your choice in accordance with the terms of the trust.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who need legal help with wills and trusts</h2>Persons who are beneficiaries under a Will or Trust but are being denied their legal share.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a will and trusts lawyer</h2>A Will and Trusts Lawyer you set up a Trust or draft a Will for your specific need.<br>A Will and Trusts Lawyer can help you apply for the Probate of a Will, Letters of Administration and Legal Heir Certificates.<br>A Will and Trusts Lawyer can help you challenge a will that was made under threat or force or was forged.<br>A Will and Trusts Lawyer can help you identify which of your properties can be made the subject of a Will or Trust which will prevent future disputes.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a will and trust lawyer through LawRato</h2>We have selected some of the best will and trust lawyers across India, to help draft your extate planning documents, or to help resolve issues arising our of will disputes and inheritance disputes.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 1,
    title: "customs-&-central-excise",
    content:
      '<section class="list-result"><h1>Consult Best Customs & Central Excise Lawyers / Advocates in India</h1><br /><p> Use LawRato to hire a top rated Customs and Central Excise lawyer in India for matters pertaining to duty evasion, customs seizure, customs clearance, excise matters and any other issues pertaining to the Central Board of Excise and Customs.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Custom and Central Excise Law in India</h2>. The Customs & Central Excise department was established in the year 1855 to administer customs laws in India and collection of import duties / land revenue.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by customs and central excise law</h2>If you are into import of goods from a foreign country into India, or have been wrongly detained by the customs department for smuggling of goods in India. <br>If you are a goods manufacturer in India and manufacture goods that are meant for home consumption. The taxable event is \'manufacture\' and the liability of central excise duty arises as soon as the goods are manufactured. It is a tax on manufacturing, which is paid by a manufacturer<br /><br /><h2 style="font-size:18px; font-weight:600;">Why you need a customs & central excise lawyer</h2>If the customs or the central excise department have hauled you for any tax evasion, or you need customs clearance, or you have an existing matter filed by the customs or the central excise department against you.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a central excise lawyer through LawRato</h2>We have selected some of the best customs and central excise laywers across India, who can help you draft your legal strategy for your business, help you in customs clearance, and resolve any matters concerning customs and central excise departments.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 2,
    title: "corporate-law",
    content:
      '<section class="list-result"><h1>Consult Best Corporate Lawyers / Advocates in India</h1><br /><p> A corporate lawyer ensures the legality of business transactions in compliance to the law, advising corporations and businesses on their legal rights and duties. Use LawRato to hire a top rated corporate lawyer in India for drafting your company\'s contracts, agreements, startup advice, mergers & acquisitions (M&A), share holder agreements and any other corporate legal requirements.<p><strong><a href=/corporate-legal target=_blank>Talk to LawRato\'s legal experts for your corporate legal requirements</a></strong></p>&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is corporate law?</h2>Corporate Law sets out the rights and liabilities of corporations, their directors, employees, creditors, and other stakeholders such as consumers.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by corporate law</h2>Business owners who wish the take advantage of business structures such as private limited companies and limited liability partnerships.<br>Minority shareholders being subjected to oppression or mismanagement by majority share holders.<br>Corporations under liquidation or other such proceedings.<br>Directors of corporations under prosecution.<br>Partners looking for company winding up, partnership dissolution or any other corporate legal requirements.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a corporate lawyer</h2>A Corporate Lawyer can represent you before specialised forums such as the Company Law Board or the Board of Industrial and Financial Reconstruction.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a corporate lawyer through LawRato</h2>We have selected some of the best corporate lawyers across India, to help draft your legal compliance documents, and provide counsel and representation in corporate legal matters for your business.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 3,
    title: "medical-negligence",
    content:
      '<section class="list-result"><h1>Consult Best Medical Negligence Lawyers / Advocates in India</h1><br /><p> To prove that you experienced medical neglience, your lawyer will file the paperwork, interview expert witnesses, and gather the evidence to build your case. Use LawRato to hire a top rated medical negligence lawyer in India who will try to get you compensation for lost wages, medical bills, and pain and suffering by filing suit against the doctor, nurse, hospital, or healthcare provider who was negligent in your treatment.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is medical negligence law?</h2>Medical Negligence Law penalises professional negligence by a health care provider in cases where the treatment provided falls below the accepted standard of practice in the medical community and can causes injury or death to the patient.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by medical negligence law</h2>Medical Negligence Law can be resorted to if either you, or a loved one, have been subjected to sub-standard medical treatment which has resulted in an injury or even death in certain cases.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a medical negligence lawyer</h2>A Medical Negligence Lawyer can help you claim compensation if you or someone in your family has been a victim of medical negligence.<br>A Medical Negligence Lawyer will also ensure that criminal proceedings are taken against the errant health care provider if required.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a medical negligence lawyer through LawRato</h2>We have handpicked some of the top medical negligence lawyers across India, to help you get justice and compensation for issues regarding medical malpractice</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 4,
    title: "recovery",
    content:
      '<section class="list-result"><h1>Consult Best Recovery Lawyers / Advocates in India</h1><br /><p> You may have lent money to family or friends in good faith, paid for services not rendered or goods that were not delivered or have quit your job and your salary dues are unpaid. Use LawRato to hire a top rated debt recovery lawyer in India to recover your lost money by sending a legal notice, filing a debt recovery suit or a summary suit or for Debt Recovery Tribunal (DRT) matters.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are recovery and debt laws?</h2>Recovery and Debt Laws prescribe rules and penalties to proceed against defaulting debtors.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by recovery and debt laws</h2>If you have taken a loan from a bank that you are unable to repay.<br>If you are owed money by any person.<br> f you are the owner of a property being foreclosed by a bank or financial institution.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a recovery and debt lawyer</h2>A Recovery and Debt Lawyer will help you file cases against defaulting debtors.<br>A Recovery and Debt Lawyer can help you by protecting your assets if you are being proceeded against by a bank or financial institution.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a debt recovery lawyer through LawRato</h2>We have shortlisted some of the top debt recovery lawyers across India, to help you get relief from creditors, and help you get you recover your debt from defaulters.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 5,
    title: "gst",
    content:
      '<section class="list-result"><h1>Consult Best GST Lawyers / Advocates in India</h1><br /><p> GST is a comprehensive indirect tax on manufacture, sale and consumption of goods and services throughout India (Except J&K) and will replace taxes levied by the central and state governments. A GST lawyer will be able to guide you on how GST will be applicable on your business and the legalities around non-compliance to GST. Use LawRato to hire a top rated GST advocate in India to get opinion on GST and its application to your business, defend you if a tax authority accuses you of under-reporting your taxes, and if you are in violation of any GST compliance in India. &nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are GST Laws?</h2>Introduction of GST is a significant step in the reform of indirect taxation in India. Amalgamating several Central and State taxes into a single tax would mitigate cascading or double taxation, facilitating a common national market. Laws governing GST and its applicability are referred to as GST laws.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by GST Laws</h2>GST will subsume various indirect taxes including central excise duty, services tax, additional customs duty, surcharges, state-level value added tax and Octroi. Businesses that currently attract any of the aforesaid taxes will fall under the ambit of GST.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a GST tax lawyer</h2>You need a GST lawyer to get opinion on GST and its application to your business. You may also consult a GST lawyer to defend you if a tax authority accuses you of under-reporting your taxes, and if you are in violation of any GST compliances.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a GST lawyer through LawRato</h2>We have selected some of the best GST lawyers across India, to help you get the correct opinion on GST applicability and to get relief from GST compliance issues.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 6,
    title: "startup",
    content:
      '<section class="list-result"><h1>Consult Best Startup Lawyers / Advocates in India</h1><br /><p> If you are a Startup that has been incorporated or have a disrupting idea and are in the planning stage, it is advisable to consult a lawyer in the initial stages itself as there are many legal aspects like the foundersâ legal rights, govt. and domain licenses, local laws, agreements with users and vendors, terms of use, privacy policies and many other related legal processes that should be addressed to avoid conflicts and legal hassles later on. Use LawRato to consult a top rated Startup lawyer in India and focus on running your startup business while your lawyer takes care of all the legal compliances.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are the laws that regulate startups?</h2>Company laws, partnership laws, trademark and intellectual property laws, licensing regimes, industry specific laws and taxation are all laws which dictate how different business should be carried out.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by laws related to startups?</h2>Anyone who wants to start a new business or invest in a new business must consider the legal framework within which the business will exist, what protections it will offer and its limitations.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a startup lawyer</h2>A Start-up Expert can help you set up your business from its inception as an idea to a fully functional unit.<br>A Start-up Expert can help incorporate a private limited company or LLP and can help you draft the constitutional documents of your business.<br>A Start-up Expert will be able to help you with registrations for trademarks, service tax, import and export and different licenses depending on the venture.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a startup lawyer through LawRato</h2>We have identified some of the best startup lawyers across India, who can help you with initial setup, company incorporation, partnership agreements, legal compliance, investments, mergers and acquisitions, ensuring your rights are protected.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 7,
    title: "motor-accident",
    content:
      '<section class="list-result"><h1>Consult Best Motor Accident Lawyers / Advocates in India</h1><br /><p> If you are involved in a car accident, a motor accident lawyer discovers who is responsible, whether insurance policies will pay for your losses, and what you can expect to recover in damages if the accident was someone else\'s fault. Use LawRato to hire a top rated motor accident lawyer in India to handle your motor accident claims tribunal (MACT) case.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is motor accident law?</h2>Motor Accident Laws require the police to compulsorily register a case in the event of a motor accident.<br>Motor Accident Laws also provide for compensation to the motor accident victims and their family. Compensation can be claimed even in cases where neither person is at fault.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by motor accident law</h2>If you or a family member has been in a road accident while driving a vehicle or even while walking on the road.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a motor accident lawyer</h2>A Motor Accident Lawyer will be able to claim compensation on your behalf by filing a petition before the Motor Accident Claims Tribunals.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a motor accident  lawyer through LawRato</h2>We have shortlisted some of the top motor accident lawyers across India, to help you get relief, compensation and damages claim in case of a motor accident.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 8,
    title: "tax",
    content:
      '<section class="list-result"><h1>Consult Best Tax Lawyers / Advocates in India</h1><br /><p> A taxation lawyer will be able to defend you if a tax authority accuses you of under-reporting your taxes, and if you are in violation of any tax law. Use LawRato to hire a top rated tax advocate in India to get opinion on direct and indirect taxation law, tax liabilities of demonetisation, service tax matters and Income Tax Appellate Tribunal (ITAT) appeals.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are taxation laws?</h2>Taxation Laws are prescribed for the payment of various taxes including income tax, general tax, service tax, sales tax etc.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by taxation laws</h2>Salaried employees, business men, providers of goods and services and even ordinary consumer can seek relief regarding tax laws<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a tax lawyer</h2>A Taxation Lawyer will help you file your returns and restructure your assets in a manner that will minimise your tax liability.<br>A Taxation Lawyer can help you challenge and set aside arbitrary claims by government authorities requiring you to pay tax.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a taxation lawyer through LawRato</h2>We have selected some of the best taxation lawyers across India, to help you get relief from excessive tax and tax compliance issues.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 9,
    title: "international-law",
    content:
      '<section class="list-result"><h1>Consult Best International Law Lawyers / Advocates in India</h1><br /><p> International lawyers deal with the agreements between individuals / corporations in India and other countries. Use LawRato to hire a top rated international lawyer in India for issues like International Commercial and Contract disputes, Cross Border disputes, Litigation Before Courts of Law Globally, International Mediation & Arbitration, Shipping Arbitration and disputes, Enforcement of international judgments in India and abroad, Personal injury claims after an accident outside of India and Family law disputes involving overseas property.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is international law?</h2>International Laws can come into play whenever a person or legal entity with foreign domicile, nationality, citizenship or origin is involved.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by international laws</h2>A person who has moved to a foreign country or has married someone or obtained a divorce in a foreign country , as well as businesses entering into cross border transactions.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need an international law expert</h2>A International Law Lawyer will be able to advise you on what laws might apply to a given case as in certain cases the law of the foreign nation may take precedence<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire an international law lawyer through LawRato</h2>We have identified some of the best international law advocates across India, to help resolve issues which deal with foreign laws and cross border transactions.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 10,
    title: "child-custody",
    content:
      '<section class="list-result"><h1>Consult Best Child Custody Lawyers / Advocates in India</h1><br /><p> A lawyer experienced in child custody cases can help you get the custody arrangement that\'s in the best interests of your child. If you\'re going through a divorce and if you and your spouse cannot come to an agreement on your child\'s custody, use LawRato to hire a top rated child custody lawyer in India to file a petition in the court on your behalf for custody.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is child custody law?</h2>Child Custody Laws ensure that a parent is not wrongfully denied access to their minor child. Child Custody Laws also protect minors from abusive parents or households.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by child custody law?</h2>A parent who is wrongly being denied access to their child either by their partner, in-laws, family members, by the Government or by any other person, institution or authority. A minor who is being victimised or abused by a member of his or her family.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a child custody lawyer</h2>A child custody lawyer will be able to protect the rights of a minor by ensuring that a parent is not wrongfully denied custody or visitation rights to the child. A child custody lawyer will also be able to protect a minor child from an abusive parent by approaching the courts for appropriate relief.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a child custody lawyer from LawRato?</h2>We have shortlisted some of the top child custody lawyers, to help you get custody of your child, child maintenance, and visitation rights.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 11,
    title: "documentaion",
    content:
      '<section class="list-result"><h1>Consult Best Documentation Lawyers / Advocates in India</h1><br /><p> The difference between a legal document drafted by an expert and a novice can be huge, and can cost a fortune. Use LawRato to hire a top rated documentation lawyer in India for due diligence, mutation, mergers, lease agreements, partnership deeds and will drafting and registration.<p><strong> <a href=/legal-documents target=_blank>Click here to download samples of common legal drafts and forms</a></strong>&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are documentation laws?</h2>Documentation laws in India are wide and varied. Almost every area of law involves some form of documentation whether it is a probate for a will, a succession certificate in property matters or a bail bond in a criminal case.<br>Even in court proceedings, documents are the only form of evidence that are required to be proved by producing the document itself and cannot be proved merely by oral testimony.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who requires a documentation lawyer</h2>Proper documentation is crucial whether you are buying a new home and want due diligence of the property papers, taking a loan or getting married.<br>A documentation lawyer can help set up businesses by drafting the required constitutional documents and contracts. <br>A documentation lawyer can also conduct property title searches to ensure that your investment in a property stays protected.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a documentation lawyer</h2>A documentation lawyer can help avoid future disputes and losses by drafting a clearly thought out agreement, will, deed or contract for you.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a documentation lawyer through LawRato</h2>We have handpicked documentation lawyers who have expertise in contract drafting, agreement drafting, will drafting, and other corporate & legal documentation, tho ensure you legal paperwork is comprehensive and iron-clad.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 12,
    title: "trademark-&-copyright",
    content:
      '<section class="list-result"><h1>Consult Best Trademark & Copyright Lawyers / Advocates in India</h1><br /><p> If you are a startup, designer, developer, or artist, there are many reasons you may need a copyright, patent & trademark lawyer on your side. You may want to protect your work, brand or mark against copy and misuse or someone may have stolen your artwork or website design or plagiarized text from your print or online article. Use LawRato to find a top rated trademark lawyer in India to file a trademark, copyright or patent of your work or to initiate proceedings against misuse or infringement of your mark or brand.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Intellectual Property Law in India</h2>Intellectual property rights include trademarks, copyrights, design rights, patents and geographical indications.<br>A trademark is commonly used to identify the source of a good or service. Intellectual property law helps prevent other businesses from copying your name, brand design and identity.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are victims of IPR infringement?</h2>Business owners, artists and inventors can all be victims of IPR infringement. <br>A business owner who"s brand name is being copied. <br>An artist whose works are being pirated. <br>An inventor who is being denied royalty for an invention.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need an IPR / trademark lawyer</h2>A IPR Lawyer will be able to help you file for registration of your IPRs which will protect your rights in the event of a future dispute. <br>An IPR Lawyer can identify and stop persons from stealing your intellectual property.<br>An IPR Lawyer can represent you in litigations or disputes which involve the infringement of intellectual property and claims for royalty.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire an IPR/TradeMark lawyer through Lawrato</h2>We have handpicked IPR and trademark lawyers across India, who will ensure your brand identity and unnique ideas are protected, and will help you get justic, if someone infringes upon your intellectual property.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 13,
    title: "civil",
    content:
      '<section class="list-result"><h1>Consult Best Civil Lawyers / Advocates in India</h1><br /><p> A civil lawyer holds experience and skills to defend individuals in civil legal matters. Use LawRatoto hire a top rated civil lawyer in India to file or defend property matters, matrimonial and family matters, recovery matters, employment matters and any other matters falling under civil law.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Civil Laws in India</h2>Laws that govern individuals in all aspects other than criminal conduct collectively are called civil laws. Civil laws include property laws, matrimonial and family laws, employment laws among others.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by civil laws</h2>Any individual who has been wronged under any civil law i.e. Property laws, matrimonial laws, family laws, labor laws to name a few.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a civil lawyer</h2>A civil lawyer can apply the required acumen and legal expertise to help you file or defend yourself in a civil suit.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a civil lawyer through LawRato</h2>We have shortlisted some of the top civil lawyers across India, to help you file or defend a property case, matrimonial case, employment related issues and any other civil matters.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 14,
    title: "supreme-court",
    content:
      '<section class="list-result"><h1>Consult Best Supreme Court Lawyers / Advocates in India</h1><br /><p> Supreme Court lawyers are amongst the most learned lawyers in the country, responsible for upholding, maintaining and consolidation of the constitutional values of democracy, rule of law and independence of Judiciary. Use LawRato to consult a top rated Supreme Court lawyer to file a Special Leave Petition (SLP), review petition, inter city transfer cases, or to file a matter that has been dismissed by the high court and needs to be appealed in the Supreme Court.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Supreme Court of India</h2>The Supreme Court of India is the highest judicial forum and final court of appeal under the Constitution of India, the highest constitutional court, with the power of constitutional review. It comprises the Chief Justice of India and 30 other judges.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who needs to approach the Supreme Court</h2>If you have a matter for which a transfer petition needs to be filed to transfer from one state to another or a matter where the high court has dismissed the matter or given a judgement against you, you can file a special leave petition or a review petition for this in the Supreme Court of India.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why you need a Supreme Court Lawyer</h2>A Supreme Court lawyer is required to draft, file and argue your matter in the Supreme Court of India. As a mandate, Advocated On Record (AOR) are required to sign the petition before it can be submitted for listing in the Supreme Court.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a Supreme Court Lawyer through LawRato</h2>We have shortlisted some of the top Supreme Court Lawyers in India to help you file and / or contest your matter in the Supreme Court of India.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 15,
    title: "tax",
    content:
      '<section class="list-result"><h1>Consult Best Banking / Finance Lawyers / Advocates in India</h1><br /><p> A banking and finance lawyer deals in matters pertaining to the borrowing and lending transactions and the laws related to it. Use LawRato to hire a top rated banking and finance lawyer in India for matters falling under Indian Contract Act, SARFAESI, DRT, RBI (including, notifications, circulars, master circulars), Transfer of Property Act or any other banking and finance legal requirements.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are banking & finance laws?</h2>Banking & Finance is a sub-category of corporate laws. It comprises of the borrowing and lending transactions, and laws related to it. The law which would apply in a "Banking and Finance" transaction would depend upon the underlying nature of the transaction. These transactions can be both domestic (on-shore i.e., where the parties are situated in India) and international transactions. Typically, Indian Contract Act, SARFAESI, DRT, RBI (including notification , circulars, master circulars),Transfer of Property Act etc, are applicable.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by banking laws?</h2>Borrowers (corporate (irrespective of size) / individual); Lenders (typically banks/ FIs) and the third party security provider (people giving, guarantee or pledge of shares or security of either movable or immovable).<br /><br /><h2 style="font-size:18px; font-weight:600;">Why you need a banking & finance lawyer</h2>Since it is a very niche practice area, expert lawyers need to have deep understanding of banking and finance laws, as well as the contents of the transaction documents, as the negotiations mostly revolve around the nature of liabilities and the obligation which are assumed under such documents. Since it also involves regulatory and statutory issues, one has to be careful that the lending and borrowing is taking place within the parameters of the rules and regulations governing that particular sector<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a banking lawyer through LawRato</h2>We have shortlisted some of the top banking and finance lawyers across India, to help you get expert advice and representation for banking and finance related legal matters.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 16,
    title: "cheque-bounce",
    content:
      '<section class="list-result"><h1>Consult Best Cheque Bounce Lawyers / Advocates in India</h1><br /><p> If you have a Cheque issued by a debtor that has bounced or has been dishonoured, or someone has issued a cheque bounce notice against you, or you have received court summons for a 138 NI (Negotiable Instruments Act) complaint against you, use LawRato to find a top rated cheque bounce lawyer in India for your needs.<br /><br /><a target="_blank" href="https://lawrato.com/send-legal-notice/cheque-bounce">Click here to Send Legal Notice for Cheque Bounce</a>&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Cheque Bounce Law in India</h2>Cheque bounce laws protect receivers of cheques in the event the cheque is return unpaid for reasons such as insufficient funds or stop payments. <br>Section 138 of the Negotiable Instruments Act (NI Act) outlines the laws governing cheque bounce matters in India.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are victims of cheque bounce fraud?</h2>Any person who has been received a cheque which has been returned unpaid for whatever reason can file a cheque bounce complaint case.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a cheque bounce lawyer</h2>A Cheque Bounce Lawyer will be able to help you recover your money by drafting a Demand Notice and further a Cheque Bounce Complaint Case if need be as required by laws.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a cheque bounce lawyer through LawRato?</h2>We have selected some of the best cheque bounce laywers across India, who can help resolve the issue through out of court settlements, and fight your case in court to recover your dues.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 17,
    title: "criminal",
    content:
      '<section class="list-result"><h1>Consult Best Criminal Lawyers / Advocates in India</h1><br /><p> Whether you are accused for a crime against a person (like assault or murder), a crime against property (like shoplifting or theft), or any other criminal offense, a criminal lawyer can help. Use LawRato to consult a top rated criminal lawyer in India to defend your rights at each stage of your case - from filing an anticipatory bail to a regular bail to an appeal after conviction or to quash an FIR.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Criminal Law in India</h2>Criminal Law covers issues such as physical assault,, theft, rape, homicide, extortion, dowry harassment, caste atrocities and financial fraud among other offences.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by criminal law?</h2>A persons who has been victim of theft, fraud, forgery or of more serious crimes such as domestic violence or rape , and persons who have been accused of a crime.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a criminal lawyer</h2>In the event of your arrest on the accusation of an offence, a Criminal Lawyer can help you secure bail or anticipatory bail.<br>A Criminal Lawyer can also help a person apprehending false accusations of an offence secure anticipatory bail. <br>A Criminal Lawyer will also set forth your trial strategy and can help identify contradictions in the case made out by the prosecution. <br>A Criminal Lawyer can help with the registration of an FIR when the police refuses to do so.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a criminal lawyer through LawRato</h2>We have shortlisted some of the most experienced criminal lawyers across the coutry, to help you get bail and relief, in case of criminal accusations, and to help you defend yourself in the court of law.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 18,
    title: "immigration",
    content:
      '<section class="list-result"><h1>Consult Best Immigration Lawyers / Advocates in India</h1><br /><p> Successfully steering your immigration case through the complex processes and numerous deadlines is extremely difficult if you don\'t have an immigration attorney. An experienced immigration attorney can prepare your petitions / applications and resolve issues on visas, green cards, and naturalization. Find LawRato to hire a top rated immigration attorney for US, UK, Canada and Dubai Immigration.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is immigration law?</h2>Immigration Laws refer to government policies which control the in-flow and out-flow of personsfrom one country to another.<br>Immigration Laws affect the legal status of a person in matters of citizenship, nationality and domicile.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by immigration law</h2>Anyone who is thinking of moving to a foreign country, even if only temporarily to study, will be affected by immigration laws.<br>You may have married a foreign national who wishes to move to your country or vice-versa. <br>All legal issues that involve the movement of people across national borders involve Immigration Laws at some level.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need an immigration lawyer</h2>A person will face several obstacles when moving to a foreign country either to study or for work or to settle down permanently. <br> An Immigration Law Expert can help you overcome several of these obstacles and can help you better understand the legal issues involved.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire an immigration lawyer through LawRato</h2>We have handpicked immigration lawyers across India and abroad, who have expertise in legal procedures for work permit, visa assistance, permanent immigration and citizenship, and can help make your immigration process easier.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 19,
    title: "insurance",
    content:
      '<section class="list-result"><h1>Consult Best Insurance Lawyers / Advocates in India</h1><br /><p> Insurance law covers the policies insurance companies offer and the rates they charge. It can take an insurance lawyer just to determine if your loss resulted from a risk you were insured for. Sometimes insurance companies deny claims, acting in what is legally called âbad faithâ. Use LawRato to hire a top rated insurance lawyer in India.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is insurance law?</h2>Insurance Laws regulate the business of Insurance and set out norms to be followed by insurance companies in selling policies and settling claims.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by insurance law</h2>A person whose claim has been wrongly rejected or delayed by an insurance company can seek relief through insurance law.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need an insurance lawyer</h2>An Insurance Lawyer may be able to compel an insurance company from approving your insurance claim if it has been wrongly rejected or delayed.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire an insurance lawyer through LawRato</h2>We have handpicked insurance lawyers across India, who have resolved numerous cases regarding delayed and rejected insurance claims, and can help you get your rightful insurance claim and compensation.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 20,
    content:
      '<section class="list-result"><h1>Consult Best Arbitration Lawyers / Advocates in India</h1><br /><p> You\'ve come to the right place if you\'d like to settle a dispute without litigation. An Arbitration / Alternative Dispute Resolution (ADR) lawyer uses out-of-court processes like arbitration, mediation or mini-trials to resolve disputes. Use LawRato to find a top rated mediation lawyer in India for ICC Arbitrations, to initiate or respond to any Arbitral Proceedings and for Alternate Dispute Resolution (ADR).&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is arbitration and reconcliliation?</h2>Arbitration and conciliation are methods of alternate dispute resolution. They allow legal disputes to be outside a Court of law.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are in need of arbitration?</h2>A person, corporation or business that wishes to resolve a legal dispute without resorting to the long drawn process of traditional litigation, or, a person or corporation party to a contract containing an arbitration clause as disputes arising from such contracts must be settled through arbitration alone.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need an arbitration lawyer</h2>An experienced Arbitration Lawyer will be able to represent you the besr in alternate dispute resolution proceedings. Also, an Arbitration Lawyer will help you get interim relief from the courts pending Arbitration and/or conciliation proceedings.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire and arbitration lawyer through LawRato?</h2>We have handpicked abritration lawyers with good experience, who will be able to ensure speedy resolution through arbitration, and also help you get interim relief during arbitration, if needed.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 21,
    content:
      '<section class="list-result"><h1>Consult Best Labour & Service Lawyers / Advocates in India</h1><br /><p> It\'s quite common nowadays for companies to withhold salary dues and delay full and final settlement of employees apart from delaying or denying promotions arbitrarily. Use LawRato to hire a top rated service and employment lawyer or a labor lawyer in India for matters like recovery of salary dues, illegal termination, sexual harassment and Central Administrative Tribunal (CAT) matters. &nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is labour law?</h2>Service and Employment Laws (labour law) dictate the duties of an employer and the rights of an employee, both in the private as well as public sector. They regulate disputes between employers and employees.<br /><br /><h2 style="font-size:18px; font-weight:600;">Whoare affected by service and labour law</h2>An employee who has been wrongfully discharged and has not been paid full & final dues and / or the company is not giving the relieving letter. <br. An employee who has not been denied retirement benefits.<br>An employer accused of wrongfully withholding dues.<br>The family of an employee that has been denied compensation.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a labour lawyer</h2>A Service and Employment Lawyer can help you get re-instated if you have been wrongfully terminated. <br>A Service and Employment Lawyer can help you claim compensation if you have been injured at work, or if your dues have been withheld or if you have been wrongfully terminated or denied promotion.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a labour lawyer through LawRato</h2>We have identified some of the best labour lawyers across India, to help resolve issues regarding wrongful termination, employer harassment, compensation delays and other service related issues.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 22,
    content:
      '<section class="list-result"><h1>Consult Best Property Lawyers / Advocates in India</h1><br /><p> Typical problems a property lawyer can resolve include illegal possession, ancestral property settlement, builder delay in possession, property disputes among family, and real estate disputes under RERA act. Use LawRato to consult a top rated property lawyer in India to file or defend a partition suit, title dispute and for due diligence of your property\'s documents.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is property law?</h2>Property Disputes Laws come into play when the title or ownership of an immovable property (such as land or an apartment) is challenged or is ambiguous.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by property law</h2>If you are the owner of a property under challenge by third persons.<br>If your property has been illegally encroached upon.<br>If you are being denied your share in an ancestral property, joint property or inheritance.<br>If your relative / siblings have taken illegal possession of your property or have encroached on your property share.<br>If youhave a collaboration deal of your property with a builder and he is not giving you the rightful possession of your property.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a property lawyer</h2>A Property Dispute Lawyer will be able to apply for an injunction which will protect your use of the property till the dispute is decided.<br>A Property Dispute Lawyer will help you conduct a title search and draw up the required paper work to ensure that your title over a property is clear.<br>A Property Dispute Lawyer can represent you in cases where the title to a property is under challenge.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a property lawyer through LawRato</h2>We have shortlisted some of the top property dispute lawyers across India, to help you claim possession, retain possession, get share in ancestral property, get share in join property and resolve property disputes.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 23,
    title: "",
    content:
      '<section class="list-result"><h1>Consult Best Consumer Court Lawyers / Advocates in India</h1><br /><p> Consumer protection lawyers handle a wide range of areas, including consumer fraud, product liability, false advertising, and other business "scams" including delayed possession or completion of builder projects. Use LawRato to find a top rated consumer court lawyer in India for your District Consumer, State Consumer Forum & National Consumer Dispute Redressal Commission (NCDRC) matters.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Consumer Protection Law in India</h2>Consumer Protection Laws provide relief to a consumer who has been provided with a defective or deficient product and/or service. Consumer Protection Laws also set up specific Consumer Courts to resolve such consumer disputes.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are victims of consumer rights violation?</h2>Anyone who has been subjected to some deficiency in a product or service can approach the consumer courts for justice, including those who are not being given possession of a flat they have purchased on time, victims of medical negligence, persons who’s insurance claims have been wrongfully denied etc.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a consumer court lawyer</h2>A Consumer Protection Lawyer will be able to secure refund and compensation for a person who has been provided with a defective or deficient product and/or service.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a consumer court lawyer through LawRato</h2>We have selected some of the best consumer laywers across India, who can help get a refund and conpensation, if your rights as a consumer have been violated.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 24,
    title: "divorce",
    content:
      '<section class="list-result"><h1>Consult Best Divorce Lawyers / Advocates in India</h1><br /><p> Hiring an experienced divorce lawyer is the best way you get peace of mind when dealing with matrimonial cases, child custody, alimony, and mutual divorce or contested divorce proceedings. Use LawRato to consult a top rated divorce lawyer for marriage issues in India to file or defend your mutual divorce petition, contested divorce, alimony, domestic violence (DV), interim maintenance, 125 CrPC, dowry harassment u/s 498a, women cell complaints or any other related matters.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Divorce Law in India</h2>There are different laws of divorce for different religion. Hindus(which includes Sikh, Jain, Budh) are governed by Hindu Marriage Act,1955.Christians are governed by Indian Divorce Act-1869 & The Indian Christian Marriage Act,1872.Muslims are governed by Personnel laws of Divorce and also the Dissolution of Marriage Act,1939 & The Muslim Women(Protection of Rights on Divorce) Act,1986. Similarly, Parsis are governed by The Parsi Marriage & Divorce Act-1936. And there is also a secular law called Special Marriage Act,1954.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are victims of divorce?</h2>A person can file for divorce in case they are unable to live with their spouse. Divorce could be with mutual consent of both parties. Contested divorce could be on grounds of adultery, domestic violence (498a), dowry demands, mental harassment or desertion.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why you need a divorce lawyer</h2>Divorce lawyers help you plan every step of your divorce. Divorce lawyers help with grounds for divorce, evidence, property division, alimony and mainenance, child custody & other issues.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a divorce lawyer through LawRato</h2>LawRato has carefully selected the top rated divorce lawyers in India. You can easily consult our divorce lawyers through phone consult, or a meeting, and decide your course of action. Every one of our divorce attorneys in India have experience in divorce laws, with well established practices.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 25,
    title: "",
    content:
      '<section class="list-result"><h1>Consult Best Cyber Crime Lawyers / Advocates in India</h1><br /><p> If a thief has stolen personal information from your computer, a cyber crime lawyer will work to halt the damage done to you, identify the culprit, and save you from further victimization. Use LawRato to hire a top rated cyber crime lawyer in India when someone uses a computer in a crime against you, such as stealing your information, committing theft, blackmailing you, or cyber-stalking.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">Cyber Crime Laws in India</h2>Cyber Crime laws in India address issues such as identity theft, corporate espionage, privacy, cyber-stalking, cyber-bullying and online fraud. India has several legislations that touch upon cyber crime.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are victims of cyber crime?</h2>Most cyber crimes that affect ordinary people involve an invasion of one’s privacy.<br>Large corporations can also fall victim to cyber espionage. Hackers can not only steal sensitive information but can also cause IT infrastructure to shut down.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a cyber crime lawyer</h2>If you are either accused of or a victim of cyber crime, a cyber crime lawyer will be able to help you navigate the complex maze of technical and legal jargon involved. <br>Cyber laws in India are often counterintuitive as we have borrowed foreign legislations which cannot be transplanted without the requisite institutional infrastructure.<br>A cyber lawyer can also help a corporation design internal security policies and guidelines.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a cyber crime lawyer through LawRato</h2>We have shortlisted the few good cyber crime lawyers in India, who can help you get justice and relief in case of online defamation, hacking, identity theft, stalking and online fraud.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 26,
    title: "armed-forces-tribunal",
    content:
      '<section class="list-result"><h1>Consult Best Armed Forces Tribunal Lawyers / Advocates in India</h1><br /><p> Armed Forces Tribunal (AFT) lawyers prosecute or defend troops court-martialed in cases of discipline or disobedience of a lawful command. Use LawRato to hire a top rated AFT lawyer in India, an army lawyer in India, navy lawyer in India, air force lawyer in India, or a military lawyer in India for matters pertaining to armed forces commission, appointment, promotion, salary raise issues and Court Martial matters.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is the armed forces law?</h2>The Armed Forces Tribunal (AFT) handles disputes and complaints with respect to commission, appointments, enrolments and conditions of service in respect of persons subject to the Army Act, 1950, The Navy Act, 1957 and the Air Force Act, 1950.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by armed forces law?</h2>Armed Forces personnel serving as the Army officer, Navy officer or Air force officer, you may need an army lawyer, navy lawyer, air force lawyer, or a military lawyer.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need an armed forces lawyer</h2>If you are an Armed Forces Personnel and have an appeal arising out of orders, findings or sentences of courts- martial held under the Armed Forces Tribunal (Procedure) rules, 2008 and for matters connected therewith or incidental thereto.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire an armed forces lawyer through LawRato</h2>We have selected some of the best armed forces lawyers across India, who have served in the armed forces previously, and have expert understanding with armed forces law and procedure.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 27,
    title: "family-dispute",
    content:
      '<section class="list-result"><h1>Consult Best Family Lawyers / Advocates in India</h1><br /><p> Whether you are filing a divorce, wanting child custody, alimony or maintenance, fighting 498a, fighting a dispute related to discord in the family, or are being harassed by your children, choose a lawyer who is an expert in family law. Use LawRato to hire a top rated family dispute lawyer in India.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What is Family Law?</h2>Family Laws regulate succession to property, inheritance, marriage, divorce, custody, alimony and adoption.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by Family Law Disputes?</h2>A person who is denied their rightful share in an inheritance or family estate. <br>A person who is being denied access to their child.<br> A person who is living with violent or abusive family members.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a family dispute lawyer</h2>A Family Lawyer can secure your rightful share in a family estate. <br>A Family Dispute Lawyer will protect your interests in the event of a disputed will or inheritance.<br>A Family Dispute Lawyer can help partition a family estate between quarrelling family members.<br>A Family Dispute Lawyer can apply for protection orders if you are being subjected to domestic violence or domestic abuse.<br>A Family Lawyer can help you get access to your child and can secure visitation rights if required.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a Family Dispute lawyer through LawRato</h2>Lawrato has carefully selected some of the best family law and family dispute lawyers across the country, to help you with legal matters of ancestral property division , propery inheritance, family abuse and family neglect.</div><br /><a href="" class="more-link">READ MORE</a>',
  },
  {
    id: 28,
    title: "",
    content:
      '<section class="list-result"><h1>Consult Best Landlord/Tenant Lawyers / Advocates in India</h1><br /><p> A landlord/tenant lawyer can help you win an eviction lawsuit, steer clear of liability, and collect or return a security deposit. Whether you are a landlord drawing up a lease or a renter trying to get back your security deposit, use LawRato to hire a top rated landlord/tenant lawyer in India.&nbsp; </p><div class="full-text"><br /><h2 style="font-size:18px; font-weight:600;">What are landlord/tenant disputes?</h2>Landlord/Tenant disputes are common where a property has been leased or given out on rent by one person to another.<br /><br /><h2 style="font-size:18px; font-weight:600;">Who are affected by landlord / tenant disputes</h2>If you are being wrongfully evicted by your landlord from a rented premises.<br>If you have not been paid arrears of rent from a tenant.<br>If a tenant is wrongly refusing to leave your property.<br>If alandlord refuses to return a security deposit.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why do you need a landlord/tenant dispute lawyer</h2>A Landlord/Tenant Dispute Lawyer will be able to protect you in the event that you are being wrongly evicted by your landlord or if you have a tenant who is wrongly refusing to leave. <br>A Landlord/Tenant Dispute Lawyer will be able to recover arrears of rent or security deposits.<br /><br /><h2 style="font-size:18px; font-weight:600;">Why hire a landlord/tenant dispute lawyer through LawRato</h2>We have handpickedsome of the top landlord/ tenant dispute lawyers across India, to help resolve issues regarding tenant squatting, tenant eviction, non-payment of rent, rent agreements and lease contracts.</div><br /><a href="" class="more-link">READ MORE</a>\n',
  },
];
